spring:
  profiles:
    active: production  # Choose either 'dev' or 'production', not both
  application:
    name: auth-service
  cloud:
    config:
      name: auth-service
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}

server:
  port: 7090
  servlet:
    context-path: /auth

jwt:
  auth:
    converter:
      resource-id: authenticationClientId

keycloak:
  realm: music
  domain: localhost:8080
  adminClientId: admin-cli
  adminClientSecret: WP0T6aYkw2w4SbpVNNkSmbY0D33LI23i
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}
