server:
  port: 7020
  servlet:
    context-path: /user

app:
  dbHostName: localhost
  dbPort: 3306
  dbUsername: ${DB_USERNAME}
  dbPassword: ${DB_PASSWORD}
  dbName: users_db
  keycloak:
    realm: bisky-music
    domain: keycloak.codewithbisky.com

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${app.keycloak.domain}/realms/${app.keycloak.realm}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${app.dbHostName}:${app.dbPort}/${app.dbName}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Rome&autoReconnect=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      validation-timeout: 5000
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  profiles:
    active: dev
  application:
    name: user-service
  cloud:
    config:
      name: user-service
  config:
    import: "optional:configserver:"

jwt:
  auth:
    converter:
      resource-id: authenticationClientId

bunny-net:
  storagePrimaryUrl: https://storage.bunnycdn.com
  storageCdnBaseUrl:
  storageZone: music
  storageUrlApiKey: ${BUNNY_API_KEY}
